[theme]
base = "light"
# primaryColor = "#FF6600"
# backgroundColor = "#FFF8F0"
# secondaryBackgroundColor = "#FDF5E6"
# textColor = "#4A3B31"
# font = "sans serif"
# borderRadius = 0.3
[browser]
gatherUsageStats = false
